#DEBIAN_PREVENT_KEYBOARD_CHANGES=yes
#
# setting the right keyboard layout
setxkbmap gb
# swap CAPS LOCK to ctrl
setxkbmap -option caps:ctrl_modifier


# playing with PATH
export PATH=$HOME/tools/maven/apache-maven-3.3.9/bin:$HOME/bin:$PATH


# Proxy settings
export http_proxy=http://<PROXY>:80
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export no_proxy=''
export NO_PROXY=$no_proxy

# virtualenvwrapper settings
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/code

# go-lang settings
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
